CREATE TABLE "appfd_place" (
"id" serial NOT NULL PRIMARY KEY,
"created" timestamp with time zone NULL,
"modified" timestamp with time zone NULL,
"attribution" varchar(500) NULL,
"enwiki_title" text NULL,
"geonames_id" integer NULL,
"osm_id" varchar(15) NULL,
"pcode" varchar(200) NULL,
"fips" integer NULL,
"admin1_code" varchar(10) NULL,
"admin2_code" varchar(65) NULL,
"admin3_code" varchar(20) NULL,
"admin4_code" varchar(15) NULL,
"admin_level" integer NULL,
"east" double precision NULL,
"north" double precision NULL,
"south" double precision NULL,
"west" double precision NULL,
"name" varchar(250) NULL,
"name_ascii" varchar(1500) NULL,
"name_display" varchar(350) NULL,
"name_en" varchar(250) NULL,
"name_normalized" varchar(2000) NULL,
"other_names" text NULL,
"geonames_feature_class" varchar(1) NULL,
"geonames_feature_code" varchar(5) NULL,
"place_type" varchar(1) NULL,
"latitude" double precision NULL,
"longitude" double precision NULL,
"mls" geometry(MULTILINESTRING,4326) NULL,
"mpoly" geometry(MULTIPOLYGON,4326) NULL,
"point" geometry(POINT,4326) NULL,
"area_sqkm" integer NULL,
"importance" double precision NULL,
"osmname_class" varchar(10) NULL,
"osmname_type" varchar(160) NULL,
"osm_type" varchar(106) NULL,
"place_rank" integer NULL,
"dem" double precision NULL,
"elevation" double precision NULL,
"city" varchar(114) NULL,
"county" varchar(91) NULL,
"country" varchar(40) NULL,
"country_code" varchar(2) NULL,
"state" varchar(120) NULL,
"street" varchar(203) NULL,
"note" varchar(200) NULL,
"population" bigint NULL,
"popularity" bigint NULL,
"timezone" varchar(30) NULL,
"topic_id" integer NULL
);